#!/usr/bin/env bash
set -xe

ORG_PATH="github.com/appc"
REPO_PATH="${ORG_PATH}/cni"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GO15VENDOREXPERIMENT=1
export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath
export CGO_ENABLED=0

echo "Building API"
go build ${REPO_PATH}/libcni

echo "Building reference CLI"
go install --ldflags '-extldflags "-static"' ${REPO_PATH}/cnitool

echo "Building plugins"

PLUGINS="plugins/meta/* plugins/main/* plugins/ipam/*"
for d in $PLUGINS; do
	if [ -d $d ]; then
		plugin=$(basename $d)
		echo "  " $plugin
		go install ${REPO_PATH}/$d
	fi
done
